"""Anki card definitions — grows by batch."""

DECK_PREFIX = "AI Digital Characters"

# Helper to reduce boilerplate
def mc(front, answer, why, deck="00_Exam_MC_Traps", sources=None, tags=None, batch="1"):
    tags = tags or []
    return {
        "deck": deck,
        "front": front,
        "back": f"<b>{answer}</b><br>{why}",
        "tags": [f"type:mc", f"batch:{batch}"] + tags,
        "sources": sources or [],
        "card_type": "mc",
    }


def basic(front, back, deck, sources, tags=None, card_type="basic", batch="1"):
    tags = tags or []
    return {
        "deck": deck,
        "front": front,
        "back": back,
        "tags": [f"type:{card_type}", f"batch:{batch}"] + tags,
        "sources": sources,
        "card_type": card_type,
    }


def calc(front, back, deck, sources, verify_id, tags=None, batch="1"):
    tags = tags or []
    return {
        "deck": deck,
        "front": front,
        "back": back,
        "tags": ["type:calc", f"batch:{batch}"] + tags,
        "sources": sources,
        "card_type": "calc",
        "verify_id": verify_id,
    }


def cloze(front, back_extra, deck, sources, tags=None, batch="1"):
    tags = tags or []
    return {
        "deck": deck,
        "front": front,
        "back": back_extra,
        "tags": ["type:cloze", f"batch:{batch}"] + tags,
        "sources": sources,
        "card_type": "cloze",
    }


CARDS: list[dict] = []

# =============================================================================
# DECK 00 — Exam 2024 Multiple Choice (19 cards)
# =============================================================================
CARDS += [
    mc(
        "The Mel scale is a linear scale that maps frequency to pitch in speech recognition.",
        "FALSE",
        "Mel is a <b>logarithmic/perceptual</b> scale: Mel = 1127·ln(1 + f/700). It approximates human pitch perception.",
        sources=["exam2024:Q1a", "L04:mel"],
        tags=["exam2024", "priority:high"],
    ),
    mc(
        "The RNN-Transducer model is designed for offline decoding and does not support streaming speech recognition.",
        "FALSE",
        "RNN-T <b>supports streaming/online</b> decoding via the prediction network and joint network with blank tokens.",
        sources=["exam2024:Q1b", "L04:architectures"],
        tags=["exam2024", "priority:high"],
    ),
    mc(
        "According to the James-Lange theory, the perception of an emotion-arousing stimulus leads simultaneously to the experience of emotion and physiological (bodily) changes.",
        "FALSE",
        "James-Lange: <b>Stimulus → Physiological response → Emotion</b> (sequential). Simultaneous emotion + body is Cannon-Bard.",
        sources=["exam2024:Q1c", "solution_ex1:2a"],
        tags=["exam2024", "priority:high"],
    ),
    mc(
        "Using convex optimization, a skin conductance signal can be decomposed into phasic and tonic components.",
        "TRUE",
        "SC decomposition into fast phasic (event-related) and slow tonic (baseline) components uses convex optimization (lecture L02).",
        sources=["exam2024:Q1d", "L02:skin_conductance"],
        tags=["exam2024", "priority:high"],
    ),
    mc(
        "In the transformer model, positional encoding is used to provide the model with information about the order of tokens in the input sequence.",
        "TRUE",
        "Self-attention is permutation-invariant; positional encodings inject <b>token position</b> information.",
        sources=["exam2024:Q1e", "solution_ex1:3c"],
        tags=["exam2024", "priority:high"],
    ),
    mc(
        "Recurrent neural networks (RNNs) can be used for tasks where the input is a sequence of tokens, such as language modeling and sequence classification.",
        "TRUE",
        "RNNs maintain hidden state across time steps — used for LM, sentiment classification, etc.",
        sources=["exam2024:Q1f", "L03:rnn"],
        tags=["exam2024"],
    ),
    mc(
        "Pruning involves removing the most impactful connections from a neural network.",
        "FALSE",
        "Pruning removes <b>least important</b> weights/neurons to compress the model while preserving performance.",
        sources=["exam2024:Q1g", "solution_ex2:2b"],
        tags=["exam2024", "priority:high"],
    ),
    mc(
        "Quantization reduces both the model size and the model accuracy.",
        "TRUE",
        "Quantization maps weights/activations to lower precision → smaller model, but typically <b>some accuracy loss</b> (though techniques like SmoothQuant mitigate this).",
        sources=["exam2024:Q1h", "L05:quantization"],
        tags=["exam2024"],
    ),
    mc(
        "Parameter-efficient fine-tuning operates only on a true subset of the model.",
        "TRUE",
        "PEFT (LoRA, adapters) freezes most weights and trains only a <b>small subset</b> of additional parameters.",
        sources=["exam2024:Q1i", "solution_ex2:1c"],
        tags=["exam2024", "priority:high"],
    ),
    mc(
        "The Griffin-Lim algorithm reconstructs the phase information iteratively from just the magnitude spectrogram without using any learned parameters.",
        "TRUE",
        "Griffin-Lim is an iterative phase-estimation algorithm — no neural network, uses magnitude spectrogram only.",
        sources=["exam2024:Q1j", "solution_ex3:3a"],
        tags=["exam2024", "priority:high"],
    ),
    mc(
        "A nuclear accent is the last accent in a phrase and is perceived as more prominent.",
        "TRUE",
        "The nuclear (phrase-final) accent is the most prominent accent in an intonation phrase.",
        sources=["exam2024:Q1k", "L08:prosody"],
        tags=["exam2024"],
    ),
    mc(
        "In FastSpeech, the speech speeds up when we repeat the encoder states by doubling the predicted duration.",
        "FALSE",
        "Repeating encoder states <b>lengthens</b> the output → speech <b>slows down</b>. Fewer repeats → faster speech.",
        sources=["exam2024:Q1l", "solution_ex3:2c"],
        tags=["exam2024", "priority:high"],
    ),
    mc(
        "Autonomous agents are characterized by their ability to operate independently, react to their environment, and plan proactively. They also have control over their internal states.",
        "TRUE",
        "Classic agent properties: autonomy, reactivity, pro-activeness, social ability (lecture L12).",
        sources=["exam2024:Q1m", "L12:agents"],
        tags=["exam2024", "priority:high"],
    ),
    mc(
        "Dialogue trees offer high flexibility in responding to unexpected queries, but they are difficult to scale and require manual design for new topics.",
        "FALSE",
        "Dialogue trees have <b>low flexibility</b> for unexpected queries; they <b>are</b> hard to scale (second part is true).",
        sources=["exam2024:Q1n", "solution_ex5:1b"],
        tags=["exam2024", "priority:high"],
    ),
    mc(
        "In a reinforcement learning algorithm, the reward should be differentiable so that we can run back-propagation to train the policy based on data.",
        "FALSE",
        "Rewards are <b>not required to be differentiable</b>. Policy gradients estimate gradients via sampled trajectories.",
        sources=["exam2024:Q1o", "solution_ex5:1e"],
        tags=["exam2024", "priority:high"],
    ),
    mc(
        "We must collect reinforcement learning trajectories from agent-environment interactions when employing Proximal Policy Optimization (PPO) to learn the policy. The collected reinforcement learning trajectories can have various lengths.",
        "TRUE",
        "PPO is on-policy: collects rollouts from current policy; trajectories can vary in length.",
        sources=["exam2024:Q1p", "L14:ppo"],
        tags=["exam2024", "priority:high"],
    ),
    mc(
        'The animation principle "Slow In and Slow Out" emphasizes linear motion.',
        "FALSE",
        "Slow In / Slow Out means <b>ease in and ease out</b> — acceleration/deceleration at start and end, not constant linear speed.",
        sources=["exam2024:Q1q", "L10:principles"],
        tags=["exam2024", "priority:high"],
    ),
    mc(
        "Facial muscles attach to a bone and connect to the skin. When they contract, they create dynamic wrinkles that form perpendicular to the direction of muscle contraction.",
        "TRUE",
        "Facial muscles attach bone-to-skin; wrinkles form <b>perpendicular</b> to contraction direction (lecture L10).",
        sources=["exam2024:Q1r", "L10:anatomy"],
        tags=["exam2024"],
    ),
    mc(
        "Linear blend skinning can handle large joint rotation angles without visual artifacts.",
        "FALSE",
        "LBS causes <b>candy-wrapper</b> twisting and volume loss at large joint angles due to linear rotation blending.",
        sources=["exam2024:Q1s", "solution_ex4:2a5"],
        tags=["exam2024", "priority:high"],
    ),
]

# =============================================================================
# DECK 00 — Exam 2025 Multiple Choice (16 cards)
# =============================================================================
CARDS += [
    mc(
        "Artifact detection is essential in affective computing because physiological signals like EEG and ECG can be contaminated by noise from muscle movements or environmental interference.",
        "TRUE",
        "Biosignals need artifact removal (movement, EMG contamination, etc.) before reliable affect inference.",
        sources=["exam2025:Q1a", "L02:artifact_detection"],
        tags=["exam2025", "priority:high"],
    ),
    mc(
        "In backpropagation, the gradient of the loss with respect to each weight is computed independently of the activation functions used in the network.",
        "FALSE",
        "Backprop uses the <b>chain rule</b> — gradients depend on activation function derivatives (ReLU, sigmoid, etc.).",
        sources=["exam2025:Q1b", "L03:neural_nets"],
        tags=["exam2025"],
    ),
    mc(
        "Discrete Fourier Transform (DFT) is commonly applied to short-time frames of a speech signal to analyze how frequency content changes over time.",
        "TRUE",
        "STFT: window speech → DFT per frame → spectrogram over time.",
        sources=["exam2025:Q1c", "L04:feature_extraction"],
        tags=["exam2025", "priority:high"],
    ),
    mc(
        "Prosody refers exclusively to the spectral features of speech, such as formants and harmonics, without involving rhythm or intonation.",
        "FALSE",
        "Prosody includes <b>pitch, duration, loudness, rhythm, intonation</b> — not just spectral features.",
        sources=["exam2025:Q1d", "solution_ex3:1c"],
        tags=["exam2025", "priority:high"],
    ),
    mc(
        "Parameter-Efficient Fine-Tuning methods (PEFT) like LoRA and adapters reduce computational cost by freezing the majority of a pre-trained model's weights and learning only a small number of additional parameters.",
        "TRUE",
        "PEFT keeps most LLM weights frozen; trains low-rank adapters or small added layers.",
        sources=["exam2025:Q1e", "solution_ex2:1c"],
        tags=["exam2025", "priority:high"],
    ),
    mc(
        "Prompt engineering can be used to implicitly control the chatbot's tone, style, and persona without modifying the underlying model.",
        "TRUE",
        "System prompts, role prompting, and style instructions shape output without weight updates.",
        sources=["exam2025:Q1f", "L06:prompting"],
        tags=["exam2025"],
    ),
    mc(
        "Hybrid fusion strategies eliminate the need for modality-specific embedding by treating all modalities identically throughout the model pipeline.",
        "FALSE",
        "Hybrid fusion <b>combines</b> early and late fusion — still uses modality-specific encoders/embeddings.",
        sources=["exam2025:Q1g", "L07:multimodality"],
        tags=["exam2025"],
    ),
    mc(
        "Stress depends on sentence context, while accent is fixed within the word.",
        "TRUE",
        "Word accent is lexical (fixed); sentence stress/placement varies with context and emphasis.",
        sources=["exam2025:Q1h", "L08:prosody"],
        tags=["exam2025"],
    ),
    mc(
        "WaveNet uses causal, dilated convolutions to model long-range temporal dependencies in sequential data such as speech.",
        "TRUE",
        "WaveNet: stacked dilated causal convolutions for autoregressive waveform generation.",
        sources=["exam2025:Q1i", "solution_ex3:3a"],
        tags=["exam2025", "priority:high"],
    ),
    mc(
        "In Linear Blend Skinning, each vertex is influenced by exactly one bone.",
        "FALSE",
        "LBS blends influences from <b>multiple bones</b> with weights w_ij summing to 1.",
        sources=["exam2025:Q1j", "solution_ex4:1c"],
        tags=["exam2025", "priority:high"],
    ),
    mc(
        "Linear interpolation between animation key frames often results in unnatural or abrupt motion rather than smooth transitions.",
        "TRUE",
        "Pure linear interpolation lacks ease-in/out → mechanical motion; Disney's Slow In/Out fixes this.",
        sources=["exam2025:Q1k", "L10:principles"],
        tags=["exam2025"],
    ),
    mc(
        "In normalizing flows, the model learns only the prior distribution pZ, while the transformation functions remain fixed.",
        "FALSE",
        "Normalizing flows learn <b>invertible transformation functions</b>; change of variables adjusts density via Jacobian determinant.",
        sources=["exam2025:Q1l", "solution_ex4:1h"],
        tags=["exam2025", "priority:high"],
    ),
    mc(
        "An autonomous agent's actions are determined solely by its immediate perception of the environment.",
        "FALSE",
        "Agents also use <b>internal state, goals, and proactive planning</b> — not perception alone.",
        sources=["exam2025:Q1m", "solution_ex5:1a"],
        tags=["exam2025", "priority:high"],
    ),
    mc(
        "A primary disadvantage of dialogue trees is their limited flexibility, which makes it difficult for them to handle unexpected user queries or engage in open-ended conversations.",
        "TRUE",
        "Dialogue trees are rigid, manually authored, poor at open-domain unexpected input.",
        sources=["exam2025:Q1n", "solution_ex5:1b"],
        tags=["exam2025", "priority:high"],
    ),
    mc(
        "In on-policy reinforcement learning, data collected from older versions of the policy can be stored in a replay buffer and reused to improve training efficiency.",
        "FALSE",
        "On-policy methods (PPO) use <b>current policy</b> data only. Replay buffers are off-policy (DQN, SAC).",
        sources=["exam2025:Q1o", "L14:rl_algorithms"],
        tags=["exam2025", "priority:high"],
    ),
    mc(
        "In the Q-learning algorithm, the policy is implicitly derived by selecting the action with the highest estimated Q-value for a given state, rather than being represented by a separate, explicit policy network.",
        "TRUE",
        "Q-learning: greedy policy π(s) = argmax_a Q(s,a); no separate policy network needed.",
        sources=["exam2025:Q1p", "L14:value_based"],
        tags=["exam2025"],
    ),
]

# =============================================================================
# DECK 00 — Exercise Multiple Choice
# =============================================================================
_ex_mc = [
    # Exercise 1
    ("Facial expression analysis and blood pressure measurement are both invasive sensing methods.", "FALSE",
     "Facial analysis is <b>non-invasive</b> (video). Blood pressure measurement is <b>invasive/interactive</b> (cuff).",
     ["solution_ex1:1a"], ["exercise1"]),
    ("Action units refer to the motion of the whole body.", "FALSE",
     "AUs are <b>facial muscle movements</b> (FACS), not whole-body motion.",
     ["solution_ex1:1b"], ["exercise1"]),
    ("ECG refers to recording electrical activity captured from the skin's surface.", "TRUE",
     "ECG electrodes on skin record heart's electrical activity.",
     ["solution_ex1:1c"], ["exercise1"]),
    ("Softmax outputs are limited to the range [−1, 1].", "FALSE",
     "Softmax outputs are in <b>[0, 1]</b> and sum to 1 (probabilities).",
     ["solution_ex1:1d"], ["exercise1"]),
    ("RNNs process all time steps simultaneously like Transformers.", "FALSE",
     "RNNs process <b>sequentially</b>; Transformers use parallel self-attention.",
     ["solution_ex1:1e"], ["exercise1", "priority:high"]),
    ("The attention mechanism assigns different weights to different parts of the input.", "TRUE",
     "Attention computes a weighted sum — higher weight = more focus.",
     ["solution_ex1:1f"], ["exercise1"]),
    ("In ADC, quantization converts real-valued numbers to positive numbers only.", "FALSE",
     "Quantization maps to a <b>finite discrete set</b> — can include negative values.",
     ["solution_ex1:1g"], ["exercise1"]),
    ("The fundamental frequency is the highest frequency component of a complex waveform.", "FALSE",
     "Fundamental frequency is the <b>lowest</b> (most dominant periodic) frequency.",
     ["solution_ex1:1h"], ["exercise1"]),
    ("A Mel filter bank consists of overlapping rectangular filters.", "FALSE",
     "Mel filters are <b>overlapping triangular</b> filters spaced on the Mel scale.",
     ["solution_ex1:1i"], ["exercise1", "priority:high"]),
    # Exercise 2
    ("Top-p sampling randomly picks from the p most likely words.", "FALSE",
     "Top-<b>p</b> (nucleus): smallest set whose cumulative prob ≥ p. Top-<b>k</b> picks k most likely.",
     ["solution_ex2:1a"], ["exercise2", "priority:high"]),
    ("More detailed prompts always lead to better AI-generated responses.", "FALSE",
     "Overly detailed/restrictive prompts can reduce creativity and flexibility.",
     ["solution_ex2:1b"], ["exercise2"]),
    ("PEFT reduces the total number of model parameters.", "FALSE",
     "PEFT trains a <b>subset</b> of params; total param count may increase (adapters) but compute cost drops.",
     ["solution_ex2:1c"], ["exercise2", "priority:high"]),
    ("In-context learning involves training with prompt-response pairs.", "FALSE",
     "ICL uses examples <b>at inference</b> without weight updates.",
     ["solution_ex2:1d"], ["exercise2", "priority:high"]),
    ("RAG supplements LLM responses with retrieved external information.", "TRUE",
     "RAG retrieves domain-specific/up-to-date docs to augment generation.",
     ["solution_ex2:1e"], ["exercise2", "priority:high"]),
    ("MOS and A/B testing are identical qualitative evaluation methods.", "FALSE",
     "MOS: absolute rating scale. A/B: <b>pairwise preference</b> comparison.",
     ["solution_ex2:1f"], ["exercise2"]),
    ("Multimodal chatbots can use user state modeling for more empathetic responses.", "TRUE",
     "Voice tone, facial expression, sentiment → adaptive empathetic responses.",
     ["solution_ex2:1g"], ["exercise2"]),
    ("Late fusion is always superior to early fusion.", "FALSE",
     "Choice depends on task; early fusion can capture cross-modal interactions better.",
     ["solution_ex2:1h"], ["exercise2"]),
    ("Chatbot personality uses the same five factors as the human Big Five model.", "FALSE",
     "Chatbot traits: <b>artificiality, conscientiousness, vibrancy, civility, neuroticism</b>.",
     ["solution_ex2:1i"], ["exercise2"]),
    # Exercise 3
    ("Text normalization is only needed to expand abbreviations like Dr. and Mr.", "FALSE",
     "Also: number expansion, punctuation disambiguation, etc.",
     ["solution_ex3:1a"], ["exercise3"]),
    ("ML models can be trained to detect sentence boundaries from punctuation context.", "TRUE",
     "Period can be abbreviation vs. sentence end — ML can disambiguate.",
     ["solution_ex3:1b"], ["exercise3"]),
    ("Prosodic analysis includes loudness but not pitch.", "FALSE",
     "Prosody includes <b>pitch (F0), duration, and loudness</b>.",
     ["solution_ex3:1c"], ["exercise3"]),
    ("Prominence in speech refers to the volume of words only.", "FALSE",
     "Prominence involves <b>pitch, duration, and sometimes loudness</b> — emphasis.",
     ["solution_ex3:1d"], ["exercise3"]),
    ("Putting two prominent accents right next to each other is known as a lapse.", "FALSE",
     "<b>Clash</b> = accents too close. <b>Lapse</b> = accents too far apart.",
     ["solution_ex3:1e"], ["exercise3", "priority:high"]),
    ("Diphone synthesis often lacks natural prosody due to limited prerecorded units.", "TRUE",
     "Small diphone inventory → less natural prosody than unit selection.",
     ["solution_ex3:1f"], ["exercise3"]),
    ("Unit selection synthesis produces more natural speech by choosing larger contextually appropriate segments.", "TRUE",
     "Selects variable-length units from recorded speech for naturalness.",
     ["solution_ex3:1g"], ["exercise3"]),
    ("Concatenative synthesis generates speech by training neural networks on text.", "FALSE",
     "Concatenative/unit selection uses <b>pre-recorded speech segments</b>.",
     ["solution_ex3:1h"], ["exercise3"]),
    ("When SYS adds a word not in REF, that is a deletion error.", "FALSE",
     "Extra word in SYS = <b>insertion</b>. Missing word = <b>deletion</b>.",
     ["solution_ex3:1i"], ["exercise3"]),
    ("MOS uses an absolute scale while A/B tests ask for comparative preference.", "TRUE",
     "MOS: 1–5 quality rating. A/B: prefer A or B.",
     ["solution_ex3:1j"], ["exercise3"]),
    # Exercise 4
    ("Stylized characters are more likely to trigger the uncanny valley than realistic characters.", "FALSE",
     "<b>Realistic</b> characters near-human are more uncanny; stylized avoids the valley.",
     ["solution_ex4:1a"], ["exercise4"]),
    ("In an articulated model, joints are only visual connectors between bones.", "FALSE",
     "Joints define <b>degrees of freedom</b> and how bones rotate/move.",
     ["solution_ex4:1b"], ["exercise4"]),
    ("In LBS, each vertex is influenced by exactly one bone.", "FALSE",
     "Vertices blend multiple bones with weights.",
     ["solution_ex4:1c"], ["exercise4", "priority:high"]),
    ("The Jacobian method is widely used for IK when analytical solutions aren't possible.", "TRUE",
     "Numerical IK via Jacobian pseudoinverse is standard.",
     ["solution_ex4:1d"], ["exercise4"]),
    ("Damping forces depend on spring stiffness.", "FALSE",
     "Damping depends on <b>velocity</b>; stiffness affects spring force.",
     ["solution_ex4:1e"], ["exercise4"]),
    ("Diverse movements are particularly important for stylized characters.", "TRUE",
     "Stylized animation emphasizes expressive, varied motion.",
     ["solution_ex4:1f"], ["exercise4"]),
    ("When m < d, manifold learning performs dimensionality reduction.", "TRUE",
     "High-dimensional data (d) projected to lower intrinsic dimension (m).",
     ["solution_ex4:1g"], ["exercise4"]),
    ("Normalizing flows use invertible functions; the Jacobian determinant adjusts density.", "TRUE",
     "Change of variables: p_X(x) = p_Z(f⁻¹(x)) · |det J_{f⁻¹}(x)|.",
     ["solution_ex4:1h"], ["exercise4", "priority:high"]),
    # Exercise 5
    ("Proactive agents primarily respond to immediate environmental changes.", "FALSE",
     "<b>Reactivity</b> = immediate response. <b>Proactiveness</b> = planning for future opportunities.",
     ["solution_ex5:1a"], ["exercise5", "priority:high"]),
    ("Dialogue trees are highly scalable for new topics.", "FALSE",
     "New topics require <b>manual design</b> — poor scalability.",
     ["solution_ex5:1b"], ["exercise5", "priority:high"]),
    ("Link prediction determines whether a relationship should exist between two entities.", "TRUE",
     "Link prediction infers missing edges in a knowledge graph.",
     ["solution_ex5:1c"], ["exercise5"]),
    ("Knowledge graph embeddings can answer queries on large incomplete graphs.", "TRUE",
     "KGE enables similarity search and link prediction when SPARQL is insufficient.",
     ["solution_ex5:1d"], ["exercise5"]),
    ("In RL, the transition model must be differentiable.", "FALSE",
     "Transition model need not be differentiable; RL handles non-differentiable simulators.",
     ["solution_ex5:1e"], ["exercise5", "priority:high"]),
    ("Monte Carlo policy gradient requires on-policy trajectories.", "TRUE",
     "Policy gradient methods collect trajectories from the current policy.",
     ["solution_ex5:1f"], ["exercise5"]),
    ("The optimal policy maximizes each individual future reward step.", "FALSE",
     "Policy maximizes <b>expected discounted return</b>, not each individual reward.",
     ["solution_ex5:1g"], ["exercise5"]),
    ("Actor-Critic methods use a value function as baseline to reduce variance.", "TRUE",
     "Critic estimates V(s) or Q(s,a) to reduce variance of policy gradient estimates.",
     ["solution_ex5:1h"], ["exercise5", "priority:high"]),
]

for front, ans, why, src, tags in _ex_mc:
    CARDS.append(mc(front, ans, why, sources=src, tags=tags))

# =============================================================================
# DECK 01 — Affective Computing
# =============================================================================
CARDS += [
    basic(
        "What is the sequence in the James-Lange theory of emotion?",
        "<b>Stimulus → Physiological response → Emotion</b><br>Example: see snake → heart races → feel fear.",
        "01_Affective_Computing",
        ["solution_ex1:2a", "exam2024:Q1c"],
        ["priority:high"],
    ),
    basic(
        "What is the Cannon-Bard theory of emotion?",
        "Physiological arousal and emotional experience occur <b>simultaneously</b> — both triggered by the stimulus in parallel (not sequentially).",
        "01_Affective_Computing",
        ["solution_ex1:2a", "exam2025:Q2a"],
        ["priority:high"],
    ),
    basic(
        "What is the Schachter-Singer (two-factor) theory of emotion?",
        "Emotion = <b>physiological arousal</b> + <b>cognitive interpretation</b> of the situation. Same arousal can yield different emotions depending on context.",
        "01_Affective_Computing",
        ["solution_ex1:2a", "exam2025:Q2a"],
    ),
    basic(
        "In the dimensional model, define valence, arousal, and dominance.",
        "<b>Valence:</b> pleasantness (+/−)<br><b>Arousal:</b> intensity/activation<br><b>Dominance:</b> sense of control vs. helplessness",
        "01_Affective_Computing",
        ["solution_ex1:2b"],
    ),
    basic(
        '"Anxious, tense, and helpless" — dimensional description?',
        "<b>Negative valence</b>, <b>high arousal</b>, <b>low dominance</b> (feeling overwhelmed, not in control).",
        "01_Affective_Computing",
        ["exam2025:Q2b"],
        ["priority:high"],
    ),
    basic(
        "What are Action Units (AUs)?",
        "Specific <b>facial muscle movements</b> from the Facial Action Coding System (FACS). Used to detect facial expressions linked to emotions.",
        "01_Affective_Computing",
        ["solution_ex1:1b", "exam2024:Q2a"],
    ),
    basic(
        "What does HRV (heart rate variability) measure and what does higher HRV suggest?",
        "HRV = variation in beat-to-beat intervals.<br><b>Higher HRV</b> → more relaxed/adaptive autonomic state, often linked to positive emotion and stress resilience.",
        "01_Affective_Computing",
        ["solution_ex1:2d", "exam2024:Q2b"],
    ),
    basic(
        "What does skin conductance (SC) measure?",
        "Electrodermal activity — sweat gland activity reflecting <b>sympathetic arousal</b>. Used as arousal indicator in affective computing.",
        "01_Affective_Computing",
        ["exam2024:Q2b", "L02:skin_conductance"],
    ),
    basic(
        "Name the four features of a phasic skin conductance response.",
        "<b>Amplitude</b> — peak height<br><b>Latency</b> — time from stimulus to response onset<br><b>Rise time</b> — time to peak<br><b>Half-recovery time</b> — time from peak to 50% recovery",
        "01_Affective_Computing",
        ["exam2024:Q2c", "L02:skin_conductance"],
        ["priority:high"],
    ),
    basic(
        "How is SC decomposed into phasic and tonic components?",
        "Using <b>convex optimization</b> to separate fast event-related phasic responses from slow tonic baseline drift.",
        "01_Affective_Computing",
        ["exam2024:Q1d", "L02:skin_conductance"],
    ),
]

# =============================================================================
# DECK 02 — Attention & Deep Learning
# =============================================================================
CARDS += [
    basic(
        "Scaled dot-product attention: formula for score and context vector?",
        "Score: s_t = (q · x_t) / √d<br>Weights: a_t = softmax(s_t)<br>Context: c = Σ_t a_t · x_t",
        "02_Attention_Deep_Learning",
        ["exam2024:Q3", "L03:attention"],
        ["priority:high"],
    ),
    basic(
        "Why does the transformer need positional encoding?",
        "Self-attention is <b>permutation-invariant</b> — without positional encoding, token order is lost.",
        "02_Attention_Deep_Learning",
        ["exam2024:Q1e", "solution_ex1:3c"],
        ["priority:high"],
    ),
    basic(
        "How do RNNs capture long-range dependencies?",
        "By maintaining a <b>hidden state</b> updated at each time step — acts as memory across the sequence.",
        "02_Attention_Deep_Learning",
        ["solution_ex1:3a"],
    ),
    calc(
        "Exam 2024 — Attention: q=[1,0,1], x₁=[1,0,0], x₂=[0,1,0], x₃=[1,1,0], d=3.<br>Compute similarity scores s_t = (q·x_t)/√d.",
        "1. s₁ = (1+0+0)/√3 = <b>1/√3 ≈ 0.577</b><br>2. s₂ = (0+0+0)/√3 = <b>0</b><br>3. s₃ = (1+0+0)/√3 = <b>1/√3 ≈ 0.577</b>",
        "02_Attention_Deep_Learning",
        ["exam2024:Q3a"],
        "attention_exam2024",
        ["priority:high"],
    ),
    calc(
        "Exam 2024 — Attention (continued): scores s₁=s₃=1/√3, s₂=0.<br>Compute attention weights via softmax.",
        "exp(1/√3) ≈ 1.947<br>exp(0) = 1<br>Sum = 1.947 + 1 + 1.947 = 4.894<br><b>a₁ ≈ 0.398, a₂ ≈ 0.204, a₃ ≈ 0.398</b>",
        "02_Attention_Deep_Learning",
        ["exam2024:Q3b"],
        "attention_exam2024",
        ["priority:high"],
    ),
    calc(
        "Exam 2024 — Attention (continued): a₁≈0.398, a₂≈0.204, a₃≈0.398.<br>Compute context vector c = Σ a_t · x_t.",
        "c = 0.398·[1,0,0] + 0.204·[0,1,0] + 0.398·[1,1,0]<br>= [0.796, 0.602, 0]<br><b>c ≈ [0.80, 0.60, 0]</b> (rounded)",
        "02_Attention_Deep_Learning",
        ["exam2024:Q3c"],
        "attention_exam2024",
        ["priority:high"],
    ),
]

# =============================================================================
# DECK 03 — Speech Recognition & Mel
# =============================================================================
CARDS += [
    basic(
        "Mel scale formula (Hz → Mel)?",
        "<b>Mel = 1127 · ln(1 + f/700)</b><br>Inverse: f = 700 · (e^(Mel/1127) − 1)",
        "03_Speech_Recognition_Mel",
        ["exam2024:Q4", "solution_ex1:4b"],
        ["priority:high"],
    ),
    basic(
        "What is Word Error Rate (WER)?",
        "WER = (S + D + I) / N<br>S=substitutions, D=deletions, I=insertions, N=words in reference.<br>Lower is better.",
        "03_Speech_Recognition_Mel",
        ["L04:wer", "solution_ex3:1i"],
        ["priority:high"],
    ),
    basic(
        "Mel filter banks: triangular filters — what are start, peak, end?",
        "For N filters, use N+2 equally spaced Mel points. Filter i peaks at point i+1, spans from point i to point i+2.",
        "03_Speech_Recognition_Mel",
        ["exam2024:Q4", "solution_ex1:4b"],
    ),
    calc(
        "Exam 2024 Mel filters: 200–8000 Hz, 3 filters, 5 Mel points (i=0..4).<br>Compute Mel endpoints and first Hz point.",
        "M_low = 1127·ln(1+200/700) ≈ <b>301 Mel</b><br>M_high = 1127·ln(1+8000/700) ≈ <b>2840 Mel</b><br>Δ = (2840−301)/4 ≈ 635<br>M₀ ≈ 301 → f₀ ≈ <b>200 Hz</b> (check: matches lower bound)",
        "03_Speech_Recognition_Mel",
        ["exam2024:Q4"],
        "mel_exam2024",
        ["priority:high"],
    ),
]

# =============================================================================
# DECK 04 — Chatbots & LLMs
# =============================================================================
CARDS += [
    basic(
        "Greedy decoding vs. top-k vs. top-p (nucleus) sampling?",
        "<b>Greedy:</b> always pick highest prob token (deterministic, repetitive).<br><b>Top-k:</b> sample from k highest-prob tokens.<br><b>Top-p:</b> sample from smallest set with cumulative prob ≥ p.",
        "04_Chatbots_LLM",
        ["exam2024:Q5", "solution_ex2:1a"],
        ["priority:high"],
    ),
    basic(
        "Three disadvantages of fine-tuning over prompt engineering?",
        "1. Requires <b>labeled data</b> and significant <b>compute</b><br>2. Risk of <b>catastrophic forgetting</b><br>3. Less flexible to update — must <b>retrain</b> for new tasks",
        "04_Chatbots_LLM",
        ["exam2024:Q5b-i"],
        ["priority:high"],
    ),
    basic(
        "Name three prompt engineering strategies and how they work.",
        "<b>Zero-shot CoT:</b> add 'Let's think step by step' to elicit reasoning.<br><b>Few-shot:</b> provide input-output examples in prompt.<br><b>Self-ask:</b> decompose into sub-questions before answering.",
        "04_Chatbots_LLM",
        ["exam2024:Q5b-ii", "solution_ex2:2d"],
        ["priority:high"],
    ),
    basic(
        "Exam 2024 prompt failure: model mimics few-shot format instead of answering. Why and fix?",
        "<b>Problem:</b> Model copies few-shot <b>pattern</b> (Question/Answer/Hint) instead of counting.<br><b>Reason:</b> Trained on internet text with Q&A formats.<br><b>Fix:</b> Clearer instructions, chain-of-thought, or fine-tune on task-specific data.",
        "04_Chatbots_LLM",
        ["exam2024:Q5b-iii"],
        ["priority:high"],
    ),
    basic(
        "Perplexity formula?",
        "PP = 2^(−(1/N) · Σ log₂ P(w_i))<br>Lower perplexity = model is less 'surprised' by the text.",
        "04_Chatbots_LLM",
        ["exam2025:Q5c-ii", "L06:perplexity"],
    ),
    calc(
        "Exam 2025 — Top-p with p=0.85. Token probs: cat=0.35, dog=0.30, runs=0.15, fast=0.10, tree=0.06, blue=0.04.<br>List candidate tokens.",
        "Cumulative: 0.35 → 0.65 → 0.80 → <b>0.90 ≥ 0.85</b><br><b>Candidates: cat, dog, runs, fast</b> (stop when cum ≥ 0.85)",
        "04_Chatbots_LLM",
        ["exam2025:Q5b-ii", "solution_ex2:2c"],
        "top_p_ex2",
        ["priority:high"],
    ),
    calc(
        "Exam 2025 — Cosine similarity: e_A=[0.5,0.1,0.4], e_B=[0.4,0.3,0.1].",
        "e_A·e_B = 0.20+0.03+0.04 = 0.27<br>|e_A| = √(0.25+0.01+0.16) = √0.42 ≈ 0.648<br>|e_B| = √(0.16+0.09+0.01) = √0.26 ≈ 0.510<br>cos = 0.27/(0.648·0.510) ≈ <b>0.82</b>",
        "04_Chatbots_LLM",
        ["exam2025:Q5c-i"],
        "cosine_exam2025",
        ["priority:high"],
    ),
    calc(
        "Exam 2025 — Perplexity of 'The cat sits quietly.' Token probs: 0.20, 0.10, 0.15, 0.25.",
        "log probs: ln(0.20)+ln(0.10)+ln(0.15)+ln(0.25) ≈ −7.20<br>PP = exp(−(−7.20)/4) = exp(1.80) ≈ <b>6.04</b>",
        "04_Chatbots_LLM",
        ["exam2025:Q5c-ii"],
        "perplexity_exam2025",
    ),
]

# =============================================================================
# DECK 05 — Speech Synthesis
# =============================================================================
CARDS += [
    basic(
        "TTS pipeline stages (in order)?",
        "1. <b>Text normalization</b><br>2. <b>Phonetic analysis</b> (G2P)<br>3. <b>Prosodic analysis</b><br>4. <b>Acoustic model</b> (mel spectrogram)<br>5. <b>Vocoder</b> (waveform)",
        "05_Speech_Synthesis",
        ["L08:pipeline", "solution_ex3"],
        ["priority:high"],
    ),
    basic(
        "What is a diphone? Why preferred over phones?",
        "A diphone spans <b>half of each adjacent phone</b> — captures coarticulation transitions. Sounds more natural than isolated phones.",
        "05_Speech_Synthesis",
        ["exam2024:Q6a-i"],
    ),
    basic(
        "Unit selection: target cost vs. join cost?",
        "<b>Target cost:</b> how well a unit matches desired acoustic features.<br><b>Join cost:</b> discontinuity at unit boundaries.<br>Minimize total cost to select best sequence.",
        "05_Speech_Synthesis",
        ["exam2024:Q6a-ii"],
    ),
    basic(
        "Tacotron 2 vs. FastSpeech — key architectural difference?",
        "<b>Tacotron 2:</b> autoregressive decoder + attention (implicit duration).<br><b>FastSpeech:</b> non-autoregressive + <b>duration predictor</b> (parallel decoding).",
        "05_Speech_Synthesis",
        ["exam2024:Q6b-ii", "solution_ex3:2a"],
        ["priority:high"],
    ),
    basic(
        "Griffin-Lim vs. WaveNet vs. HiFi-GAN?",
        "<b>Griffin-Lim:</b> iterative phase recovery, no training, fast but robotic.<br><b>WaveNet:</b> autoregressive neural, high quality, slow.<br><b>HiFi-GAN:</b> GAN vocoder, parallel, real-time, near WaveNet quality.",
        "05_Speech_Synthesis",
        ["exam2024:Q6b-iii", "solution_ex3:3a"],
        ["priority:high"],
    ),
    basic(
        "DiffWave: forward process, reverse process, conditioning?",
        "<b>Forward:</b> add Gaussian noise over steps.<br><b>Reverse:</b> iteratively denoise, predict noise at each step.<br><b>Conditioned on:</b> mel spectrogram.",
        "05_Speech_Synthesis",
        ["exam2025:Q6b-ii", "solution_ex3:3d"],
    ),
    basic(
        "Why learned speaker embeddings over one-hot in multi-speaker TTS?",
        "Embeddings capture <b>continuous similarity</b> between speakers, enable interpolation, and generalize better than sparse one-hot vectors.",
        "05_Speech_Synthesis",
        ["exam2025:Q6b-iii", "solution_ex3:4a"],
    ),
]

# =============================================================================
# DECK 06 — Knowledge Graphs
# =============================================================================
CARDS += [
    basic(
        "Standard format for knowledge graphs?",
        "<b>RDF triples:</b> (subject, predicate, object) — e.g. (Dr. Clark, affiliatedWith, CS Dept).",
        "06_Knowledge_Graphs",
        ["exam2024:Q7a", "L12:kg"],
        ["priority:high"],
    ),
    basic(
        "SPARQL: what is it used for?",
        "W3C standard <b>query language</b> for RDF knowledge graphs. Pattern matching with SELECT/WHERE.",
        "06_Knowledge_Graphs",
        ["exam2024:Q7b", "solution_ex5:2b"],
        ["priority:high"],
    ),
    basic(
        "Massive incomplete KG: what approach instead of exact SPARQL?",
        "<b>Knowledge graph embeddings</b> (TransE, TransR) — represent entities/relations as vectors for link prediction and similarity queries.",
        "06_Knowledge_Graphs",
        ["exam2024:Q7b", "L12:kge"],
        ["priority:high"],
    ),
    basic(
        "TransE scoring function?",
        "For triple (h, r, t): score = <b>||h + r − t||</b> (L1 or L2 norm).<br>Lower score = more likely true. Training: minimize score for true triples.",
        "06_Knowledge_Graphs",
        ["exam2025:Q7c", "solution_ex5:2c"],
        ["priority:high"],
    ),
    basic(
        "Why can't TransE represent symmetric relations well?",
        "TransE models r as <b>translation</b>: h + r ≈ t. For symmetric r: h + r ≈ t AND t + r ≈ h implies r ≈ 0 — can't capture meaningful symmetric relations.",
        "06_Knowledge_Graphs",
        ["exam2025:Q7c-iii"],
        ["priority:high"],
    ),
    calc(
        "Exam 2025 TransE: h=[2.0,1.5,−0.5], r=[−0.2,−0.7,0.3], t=[1.8,0.8,−0.2].<br>Score for (h, supervise, t)?",
        "h + r = [1.8, 0.8, −0.2] = t<br>h + r − t = [0, 0, 0]<br>||h+r−t||₂ = <b>0.0</b> (well below threshold 2.0 → likely true)",
        "06_Knowledge_Graphs",
        ["exam2025:Q7c-i"],
        "transe_exam2025",
        ["priority:high"],
    ),
]

# =============================================================================
# DECK 07 — Reinforcement Learning
# =============================================================================
CARDS += [
    basic(
        "Define MDP components: state, action, reward, policy, return.",
        "<b>State s:</b> environment observation<br><b>Action a:</b> agent's choice<br><b>Reward r:</b> scalar feedback<br><b>Policy π(a|s):</b> action distribution<br><b>Return R:</b> discounted sum of rewards",
        "07_Reinforcement_Learning",
        ["exam2024:Q8", "exam2025:Q8", "L14:mdp"],
        ["priority:high"],
    ),
    basic(
        "Q(s,a) and V(s) relationship?",
        "Q(s,a) = expected return from taking action a in state s.<br>V(s) = E_{a~π}[Q(s,a)] = Σ_a π(a|s)·Q(s,a).",
        "07_Reinforcement_Learning",
        ["exam2025:Q8c", "L14:value_functions"],
        ["priority:high"],
    ),
    basic(
        "Three advantages of PPO + Actor-Critic over vanilla policy gradient?",
        "1. <b>Critic baseline</b> reduces variance<br>2. <b>Clipped surrogate</b> prevents destructively large updates<br>3. <b>Sample efficiency</b> via multiple epochs on same batch",
        "07_Reinforcement_Learning",
        ["exam2025:Q8d", "L14:ppo"],
        ["priority:high"],
    ),
    basic(
        "Why use RL instead of supervised learning for physics simulation tasks?",
        "Simulation is typically <b>non-differentiable</b> — can't backprop through physics. RL learns from trial-and-error rewards.",
        "07_Reinforcement_Learning",
        ["solution_ex5:3a", "L14:applications"],
        ["priority:high"],
    ),
]

# =============================================================================
# DECK 08 — Animation
# =============================================================================
CARDS += [
    basic(
        "Forward kinematics vs. inverse kinematics?",
        "<b>FK:</b> given joint angles → compute end-effector position.<br><b>IK:</b> given target position → compute joint angles.",
        "08_Animation",
        ["solution_ex4:2a", "exam2024:Q9"],
        ["priority:high"],
    ),
    basic(
        "Jacobian IK update formula?",
        "Δθ = α · J⁺ · Δe<br>where Δe = target − current end-effector, J⁺ = pseudoinverse of Jacobian, α = learning rate.",
        "08_Animation",
        ["solution_ex4:2b", "exam2024:Q9"],
        ["priority:high"],
    ),
    basic(
        "What is the candy-wrapper artifact in LBS?",
        "At large joint rotations, linear blend skinning causes <b>unnatural twisting</b> and volume loss around the joint axis.",
        "08_Animation",
        ["solution_ex4:2a5", "exam2024:Q1s"],
        ["priority:high"],
    ),
    basic(
        "What is DeepPhase's core idea?",
        "Learns <b>phase-aware</b> periodic motion representations via autoencoder — captures motion manifolds for data-driven animation synthesis and editing.",
        "08_Animation",
        ["exam2024:Q9b", "exam2025:Q9b-i", "solution_ex4:3a"],
        ["priority:high"],
    ),
    basic(
        "Normalizing flows — main idea and one animation application?",
        "Learn <b>invertible</b> mappings from simple prior to complex data distribution; exact likelihood via Jacobian determinant.<br><b>Application:</b> diverse motion generation with temporal consistency.",
        "08_Animation",
        ["exam2025:Q9b-ii", "solution_ex4:1h"],
    ),
    calc(
        "Exam 2024 IK: L1=5, L2=4, θ₁=θ₂=π/2, target [5,5], α=0.1.<br>Compute initial end-effector e₀.",
        "e₀ = [5·cos(π/2)+4·cos(π), 5·sin(π/2)+4·sin(π)]<br>= [0+(−4), 5+0] = <b>[−4, 5]</b>",
        "08_Animation",
        ["exam2024:Q9a-i", "solution_ex4:2b"],
        "ik_ex4",
        ["priority:high"],
    ),
    calc(
        "Exam 2024 IK (continued): e₀=[−4,5], target [5,5]. Compute Δe.",
        "Δe = [5,5] − [−4,5] = <b>[9, 0]</b>",
        "08_Animation",
        ["exam2024:Q9a-ii", "solution_ex4:2b"],
        "ik_ex4",
    ),
    calc(
        "Exam 2024 IK (continued): J⁺=[[−0.2,0],[0.2,−0.25]], Δe=[9,0], α=0.1.<br>Compute Δθ.",
        "Δθ = 0.1 · J⁺ · Δe = 0.1 · [−1.8, 1.8] = <b>[−0.18, 0.18]</b>",
        "08_Animation",
        ["exam2024:Q9a-iv", "solution_ex4:2b"],
        "ik_ex4",
        ["priority:high"],
    ),
]

# =============================================================================
# BATCH 2 — Affective Computing, Deep Learning, Speech Recognition (deep dive)
# Sources: solution_ex1, L02, L03, L04, exam2025:Q2-Q3
# =============================================================================

CARDS += [
    # --- 01 Affective Computing ---
    basic(
        "Ekman's six basic emotions?",
        "Joy, Sadness, Disgust, Surprise, Anger, Fear",
        "01_Affective_Computing",
        ["L02:basic_emotions"],
        batch="2",
    ),
    basic(
        "Which Action Units indicate Happiness (Ekman/FACS)?",
        "<b>AU6</b> (Cheek Raiser) + <b>AU12</b> (Lip Corner Puller)",
        "01_Affective_Computing",
        ["L02:AU_table"],
        batch="2",
    ),
    basic(
        "Which Action Units indicate Surprise?",
        "<b>AU1</b> (Inner Brow Raiser) + <b>AU2</b> (Outer Brow Raiser) + <b>AU5</b> (Upper Lid Raiser) + <b>AU26</b> (Jaw Drop)",
        "01_Affective_Computing",
        ["L02:AU_table"],
        batch="2",
    ),
    basic(
        "Mouth Aspect Ratio (MAR) formula?",
        "MAR = (|p₂−p₈| + |p₃−p₇| + |p₄−p₆|) / (3 · |p₅−p₁|)<br>Uses facial landmarks; measures mouth openness.",
        "01_Affective_Computing",
        ["L02:MAR", "exam2024:Q2a"],
        batch="2",
    ),
    basic(
        "How is fidgeting detected from video? (4 steps)",
        "1. f_temp = f_gray − b_gray<br>2. Binarize f_temp (threshold)<br>3. Energy E = % surviving pixels<br>4. Update background: b = (1−α)b + α·f_gray",
        "01_Affective_Computing",
        ["L02:fidgeting", "solution_ex1:2c"],
        ["priority:high"],
        batch="2",
    ),
    calc(
        "Exercise 1 fidgeting: 9 pixels, 8 survive threshold. Compute Energy E (%).",
        "E = (surviving pixels / total pixels) × 100 = 8/9 × 100 = <b>88.89%</b>",
        "01_Affective_Computing",
        ["solution_ex1:2c"],
        "fidget_energy_ex1",
        batch="2",
    ),
    basic(
        "What does OpenFace output?",
        "68 facial landmarks, AU intensities [0,5], AU presence (binary), eye gaze, head pose.",
        "01_Affective_Computing",
        ["L02:OpenFace"],
        batch="2",
    ),
    basic(
        "How are eye blinks detected?",
        "Based on <b>AU45</b> (eye blink), evaluated per frame — intensity and blink events.",
        "01_Affective_Computing",
        ["L02:eye_blinks"],
        batch="2",
    ),
    basic(
        "Give examples of non-invasive vs. invasive emotion sensing.",
        "<b>Non-invasive:</b> facial video, speech, text, ECG/SC on skin surface.<br><b>Invasive:</b> hormone levels, neurotransmitter levels (blood/internal).",
        "01_Affective_Computing",
        ["L02:emotion_recognition", "solution_ex1:1a"],
        batch="2",
    ),
    basic(
        "ECG vs. PPG — what does each measure?",
        "<b>ECG:</b> electrical activity of heart from skin electrodes.<br><b>PPG:</b> light reflected by blood vessels (can use webcam on skin/pupil).",
        "01_Affective_Computing",
        ["L02:cardiac"],
        batch="2",
    ),
    basic(
        "Name three time-domain HRV measures.",
        "1. Standard deviation of R-R intervals<br>2. RMSSD (root mean square of successive differences)<br>3. pNN50 (% successive RR diffs > 50 ms)",
        "01_Affective_Computing",
        ["L02:HRV"],
        batch="2",
    ),
    calc(
        "Exercise 1 HRV: seq1={72,75,70,73,76}. Compute mean and σ (std dev).",
        "Mean x̄ = 366/5 = <b>73.2</b><br>σ = √(22.8/5) ≈ <b>2.14</b> → lower HRV, possibly stress/anxiety.",
        "01_Affective_Computing",
        ["solution_ex1:2d"],
        "hrv_std_ex1",
        batch="2",
    ),
    calc(
        "Exercise 1 HRV: seq2={74,71,76,79,80}. Compute σ.",
        "Mean x̄ = <b>76</b><br>σ = √(54/5) ≈ <b>3.29</b> → higher HRV, relaxed/adaptive state.",
        "01_Affective_Computing",
        ["solution_ex1:2d"],
        "hrv_std2_ex1",
        batch="2",
    ),
    basic(
        "Tonic vs. phasic skin conductance?",
        "<b>Tonic:</b> slow baseline level (overall arousal).<br><b>Phasic:</b> fast event-related responses (peaks after stimuli). Decomposed via convex optimization (cvxEDA).",
        "01_Affective_Computing",
        ["L02:skin_conductance", "exam2024:Q1d"],
        ["priority:high"],
        batch="2",
    ),
    basic(
        "Artifact detection for R-R intervals: define QD, MAD, MED, CBD.",
        "QD = (Q3−Q1)/2<br>MAD = (Median Beat − 2.9·QD)/3<br>MED = 3.32·QD<br>CBD = (MAD + MED)/2<br>If |RRᵢ − last valid| > CBD → artifact.",
        "01_Affective_Computing",
        ["L02:artifact_detection", "exam2025:Q2c"],
        ["priority:high"],
        batch="2",
    ),
    calc(
        "Exam 2025: R-R interval 400 ms. Heart rate in bpm?",
        "HR = 60000 / RR_ms = 60000/400 = <b>150 bpm</b> (unusually high → suspicious).",
        "01_Affective_Computing",
        ["exam2025:Q2c-i"],
        "hr_rr_exam2025",
        batch="2",
    ),
    calc(
        "Exam 2025 artifact: RR={795,800,400,810,800,805}. Q1=795, Q3=805, median=800.<br>Compute CBD. Is 400 ms an artifact vs. last valid 800 ms?",
        "QD = (805−795)/2 = <b>5</b><br>MAD = (800−2.9·5)/3 = <b>261.83</b><br>MED = 3.32·5 = <b>16.60</b><br>CBD = (261.83+16.60)/2 = <b>139.22</b><br>|400−800| = 400 > CBD → <b>artifact</b>",
        "01_Affective_Computing",
        ["exam2025:Q2c-ii", "L02:artifact_detection"],
        "artifact_exam2025",
        ["priority:high"],
        batch="2",
    ),
    basic(
        "Self-Assessment Manikin (SAM) — what three dimensions?",
        "Valence, Arousal, Dominance — used as ground truth for affect labeling.",
        "01_Affective_Computing",
        ["L02:SAM"],
        batch="2",
    ),
    basic(
        "Boredom in the dimensional model?",
        "<b>Low valence</b> (mildly unpleasant), <b>low arousal</b> (passive), <b>medium-to-low dominance</b>.",
        "01_Affective_Computing",
        ["solution_ex1:2b"],
        batch="2",
    ),
    basic(
        "Video-based emotion recognition pipeline (4 stages)?",
        "Preprocessing (frame rate, brightness) → Feature extraction (AUs, gaze, MAR, fidgeting) → Classification (valence/arousal) → Output",
        "01_Affective_Computing",
        ["L02:video_pipeline"],
        batch="2",
    ),
    basic(
        "Basic emotions theory (Ekman) — three key claims?",
        "1. Caused by phylogenetic event categories<br>2. Elicit physiological + expressive signals<br>3. Trigger innate action plans (fight/flight)",
        "01_Affective_Computing",
        ["L02:basic_emotions_theory"],
        batch="2",
    ),

    # --- 02 Deep Learning ---
    basic(
        "Neural network unit: formulas for z and output a?",
        "z = w·x + b (weighted sum)<br>a = σ(z) (activation function applied to z)",
        "02_Attention_Deep_Learning",
        ["L03:neural_unit"],
        batch="2",
    ),
    calc(
        "Exercise 1: w=[2.2,−3,1.5], x=[0,5,8], b=3, ReLU activation. Compute output.",
        "z = 2.2·0 + (−3)·5 + 1.5·8 + 3 = 0<br>ReLU(0) = <b>0</b>",
        "02_Attention_Deep_Learning",
        ["solution_ex1:3b"],
        "relu_ex1",
        batch="2",
    ),
    basic(
        "Why do standard RNNs suffer from vanishing gradients?",
        "Repeated multiplication of gradients through many time steps → gradients shrink exponentially, so long-range dependencies are hard to learn.",
        "02_Attention_Deep_Learning",
        ["exam2025:Q3a-ii", "L03:rnn_problems"],
        ["priority:high"],
        batch="2",
    ),
    basic(
        "LSTM gating mechanism — three gates and their role?",
        "<b>Forget gate:</b> what to discard from cell state.<br><b>Input gate:</b> what new info to store.<br><b>Output gate:</b> what to output.<br>Cell state highway mitigates vanishing gradients.",
        "02_Attention_Deep_Learning",
        ["exam2025:Q3a-iii", "L03:LSTM"],
        ["priority:high"],
        batch="2",
    ),
    basic(
        "Encoder-decoder architecture — how does it work?",
        "Encoder maps input sequence (x₁…x_T) to context vector h_T.<br>Decoder uses h_T to initialize autoregressive generation of output sequence (y₁…y_m).",
        "02_Attention_Deep_Learning",
        ["L03:encoder_decoder"],
        batch="2",
    ),
    basic(
        "Teacher forcing vs. inference in encoder-decoder training?",
        "<b>Training:</b> feed gold previous token y_{t−1} as decoder input.<br><b>Inference:</b> feed model's own previous prediction ŷ_{t−1}.",
        "02_Attention_Deep_Learning",
        ["L03:teacher_forcing"],
        batch="2",
    ),
    basic(
        "Self-attention vs. cross-attention in Transformers?",
        "<b>Self-attention:</b> Q,K,V from same sequence (encoder or masked decoder).<br><b>Cross-attention:</b> Q from decoder, K,V from encoder output.",
        "02_Attention_Deep_Learning",
        ["L03:attention", "L03:transformers"],
        batch="2",
    ),
    basic(
        "Why masked multi-head attention in the Transformer decoder?",
        "Prevents positions from attending to <b>future</b> tokens — at test time future tokens are unknown (no cheating).",
        "02_Attention_Deep_Learning",
        ["L03:masked_attention"],
        ["priority:high"],
        batch="2",
    ),
    basic(
        "Purpose of multi-head attention?",
        "Multiple attention heads let the model attend to <b>different types of relationships</b> simultaneously (e.g., syntactic vs. semantic).",
        "02_Attention_Deep_Learning",
        ["L03:multi_head"],
        batch="2",
    ),
    basic(
        "Transformer skip connections and layer normalization — why?",
        "<b>Skip connections:</b> h_res = c + e — eases gradient flow.<br><b>Layer norm:</b> normalizes across sequence dimension per example (not batch norm).",
        "02_Attention_Deep_Learning",
        ["L03:transformers"],
        batch="2",
    ),
    cloze(
        "Sinusoidal positional encoding: PE(t,2i) = {{c1::sin(t/10000^(2i/d))}}, PE(t,2i+1) = {{c2::cos(t/10000^(2i/d))}}",
        "Added to token embedding: ê_t = e_t + PE(t). Gives unique position signal without recurrence.",
        "02_Attention_Deep_Learning",
        ["L03:positional_encoding", "solution_ex1:3c"],
        batch="2",
    ),
    calc(
        "Exercise 1 attention: q=[3,1], k₁=[1,2], k₂=[2,0], d=2.<br>Compute scaled dot-product scores.",
        "s₁ = (3·1+1·2)/√2 = 5/√2 ≈ <b>3.54</b><br>s₂ = (3·2+1·0)/√2 = 6/√2 ≈ <b>4.24</b>",
        "02_Attention_Deep_Learning",
        ["solution_ex1:3d"],
        "attention_ex1_scores",
        batch="2",
    ),
    calc(
        "Exercise 1 attention (cont.): scores≈[3.54, 4.24]. Softmax weights?",
        "a₁ = e^3.54/(e^3.54+e^4.24) ≈ <b>0.331</b><br>a₂ ≈ <b>0.669</b>",
        "02_Attention_Deep_Learning",
        ["solution_ex1:3d"],
        "attention_ex1_weights",
        batch="2",
    ),
    calc(
        "Exercise 1 attention (cont.): v₁=[0,3], v₂=[1,1], weights 0.331/0.669.<br>Context vector?",
        "c = 0.331·[0,3] + 0.669·[1,1] = <b>[0.669, 1.662]</b>",
        "02_Attention_Deep_Learning",
        ["solution_ex1:3d"],
        "attention_ex1_context",
        batch="2",
    ),
    calc(
        "Exam 2025: X=[[1,2],[3,4]], PE(pos,0)=sin(pos), PE(pos,1)=cos(pos).<br>Compute X̂ (embeddings + PE) for positions 0 and 1.",
        "PE(0)=[sin(0),cos(0)]=[0,1] → x̂₀=[1,2]+[0,1]=<b>[1,3]</b><br>PE(1)=[sin(1),cos(1)]≈[0.84,0.54] → x̂₁=[3,4]+[0.84,0.54]=<b>[3.84,4.54]</b>",
        "02_Attention_Deep_Learning",
        ["exam2025:Q3b-i"],
        "transformer_pe_exam2025",
        ["priority:high"],
        batch="2",
    ),
    basic(
        "Bidirectional RNN — how does it work?",
        "Two RNNs: left-to-right and right-to-left on the sequence. Hidden states combined (concat/add/multiply) so each position sees both past and future context.",
        "02_Attention_Deep_Learning",
        ["L03:bidirectional_rnn"],
        batch="2",
    ),
    basic(
        "RNN sequence classification — which hidden state is used?",
        "Typically the <b>last token's hidden state</b> h_T (e.g., for sentiment classification).",
        "02_Attention_Deep_Learning",
        ["L03:sequence_classification"],
        batch="2",
    ),
    basic(
        "What is backpropagation through time (BPTT)?",
        "Unfold RNN over time steps and apply standard backprop across the unfolded graph to train shared weights U, V, W.",
        "02_Attention_Deep_Learning",
        ["L03:BPTT"],
        batch="2",
    ),

    # --- 03 Speech Recognition ---
    basic(
        "What is a phone in speech recognition?",
        "A speech sound represented by a symbol (ARPAbet/IPA). A string of phones = pronunciation of a word.",
        "03_Speech_Recognition_Mel",
        ["L04:phonetics"],
        batch="2",
    ),
    basic(
        "Relationship between F0, pitch, and the Mel scale?",
        "F0 = lowest frequency of periodic waveform. <b>Pitch</b> = perceptual correlate of F0 (not linear above ~1 kHz). <b>Mel scale</b> models perceived pitch spacing.",
        "03_Speech_Recognition_Mel",
        ["L04:pitch"],
        ["priority:high"],
        batch="2",
    ),
    calc(
        "Exercise 1 speech: waveform period T=0.2 s, max amplitude A=2.<br>Compute frequency f and identify amplitude.",
        "f = 1/T = 1/0.2 = <b>5 Hz</b><br>Amplitude A = <b>2</b> (max value on y-axis).",
        "03_Speech_Recognition_Mel",
        ["solution_ex1:4a"],
        "waveform_ex1",
        batch="2",
    ),
    basic(
        "Speech feature extraction pipeline (after windowing)?",
        "Window speech → <b>DFT/FFT</b> per frame → power spectrum → <b>Mel filter bank</b> → log → feature vector (e.g. 80-dim).",
        "03_Speech_Recognition_Mel",
        ["L04:feature_extraction"],
        ["priority:high"],
        batch="2",
    ),
    basic(
        "Typical windowing parameters for speech?",
        "Window size: <b>20–40 ms</b>. Stride: ~<b>50%</b> overlap. Hamming window reduces spectral leakage at frame edges.",
        "03_Speech_Recognition_Mel",
        ["L04:windowing"],
        batch="2",
    ),
    basic(
        "Hamming window formula and purpose?",
        "w(n) = 0.54 − 0.46·cos(2πn/(N−1))<br>Tapers frame edges → minimizes discontinuities and spectral leakage.",
        "03_Speech_Recognition_Mel",
        ["L04:hamming"],
        batch="2",
    ),
    basic(
        "Mel filter bank construction — 5 steps?",
        "1. Convert f_low, f_high to Mel<br>2. Space N+2 points linearly in Mel<br>3. Convert back to Hz<br>4. Round to FFT bins<br>5. Create overlapping triangular filters (peak at center point)",
        "03_Speech_Recognition_Mel",
        ["L04:mel_construction", "exam2024:Q4"],
        ["priority:high"],
        batch="2",
    ),
    calc(
        "Exercise 1 Mel: 100–2000 Hz, 4 filters (6 Mel points).<br>M_low and M_high?",
        "M_low = 1127·ln(1+100/700) ≈ <b>150.36 Mel</b><br>M_high = 1127·ln(1+2000/700) ≈ <b>1521.45 Mel</b>",
        "03_Speech_Recognition_Mel",
        ["solution_ex1:4b"],
        "mel_ex1_endpoints",
        batch="2",
    ),
    calc(
        "Exercise 1 Mel (cont.): ΔM=(1521.45−150.36)/5≈274.22.<br>List M₀…M₅ and Hz equivalents.",
        "M: 150, 425, 699, 973, 1247, 1521<br>Hz: <b>100, 320, 600, 959, 1415, 2000</b>",
        "03_Speech_Recognition_Mel",
        ["solution_ex1:4b"],
        "mel_ex1_points",
        ["priority:high"],
        batch="2",
    ),
    basic(
        "Exercise 1 Mel: define 4 triangular filters from 6 Hz points.",
        "Filter 1: 100–320–600 Hz<br>Filter 2: 320–600–959 Hz<br>Filter 3: 600–959–1415 Hz<br>Filter 4: 959–1415–2000 Hz",
        "03_Speech_Recognition_Mel",
        ["solution_ex1:4b"],
        batch="2",
    ),
    calc(
        "Exam 2024 Mel: 200–8000 Hz, 3 filters, 5 Mel points.<br>List all 5 Hz boundary points.",
        "M_low≈301, M_high≈2840, Δ≈635<br>Hz: <b>200, 887, 2098, 4234, 8000</b>",
        "03_Speech_Recognition_Mel",
        ["exam2024:Q4"],
        "mel_exam2024_full",
        ["priority:high"],
        batch="2",
    ),
    calc(
        "Exercise 1 WER case 1: REF has 6 words, 2 substitutions (a→at, towel→all). WER?",
        "WER = 100 × (2+0+0) / 6 = <b>33.3%</b>",
        "03_Speech_Recognition_Mel",
        ["solution_ex1:4c"],
        "wer_ex1_case1",
        batch="2",
    ),
    calc(
        "Exercise 1 WER case 2: REF has 8 words, 2 substitutions + 1 insertion. WER?",
        "WER = 100 × 3/8 = <b>37.5%</b>",
        "03_Speech_Recognition_Mel",
        ["solution_ex1:4c"],
        "wer_ex1_case2",
        batch="2",
    ),
    basic(
        "CTC (Connectionist Temporal Classification) — key ideas?",
        "Outputs per frame incl. <b>blank</b> token. Collapse consecutive duplicates → many alignments map to same output. Training uses dynamic programming over alignments.",
        "03_Speech_Recognition_Mel",
        ["L04:CTC"],
        batch="2",
    ),
    basic(
        "RNN-Transducer — three components?",
        "1. <b>Encoder</b> (acoustic model)<br>2. <b>Predictor</b> (language model, conditions on output so far)<br>3. <b>Joiner</b> (feedforward network combining encoder + predictor)",
        "03_Speech_Recognition_Mel",
        ["L04:RNN-T"],
        ["priority:high"],
        batch="2",
    ),
    basic(
        "Why does RNN-Transducer support streaming?",
        "Online decoding: increment output index u on non-blank token, increment acoustic index t on blank — processes audio incrementally.",
        "03_Speech_Recognition_Mel",
        ["L04:RNN-T", "exam2024:Q1b"],
        ["priority:high"],
        batch="2",
    ),
    basic(
        "Speech training augmentation — three types?",
        "<b>Time warping</b> (distort time axis)<br><b>Frequency masking</b> (mask mel bands)<br><b>Time masking</b> (mask time frames)",
        "03_Speech_Recognition_Mel",
        ["L04:augmentation"],
        batch="2",
    ),
    basic(
        "Analog-to-digital conversion — two steps?",
        "<b>Sampling:</b> discrete time points.<br><b>Quantization:</b> map continuous amplitudes to finite discrete values (can be positive or negative).",
        "03_Speech_Recognition_Mel",
        ["solution_ex1:1g", "L04:adc"],
        batch="2",
    ),
    basic(
        "Why subsample acoustic features in encoder-decoder ASR?",
        "Input acoustic sequence is much longer than output token sequence — subsampling (low frame rate, CNN pooling, pyramidal RNN) compresses time dimension.",
        "03_Speech_Recognition_Mel",
        ["L04:subsampling"],
        batch="2",
    ),
    basic(
        "WER: define substitution, insertion, deletion.",
        "<b>Substitution:</b> wrong word in place of REF word.<br><b>Insertion:</b> extra word in SYS not in REF.<br><b>Deletion:</b> REF word missing from SYS.",
        "03_Speech_Recognition_Mel",
        ["L04:WER", "solution_ex3:1i"],
        batch="2",
    ),
    calc(
        "Exam 2024 Mel: Hz points 200, 887, 2098, 4234, 8000 (3 filters).<br>Define filter 1 and filter 2 (start–peak–end).",
        "Filter 1: <b>200 – 887 – 2098 Hz</b><br>Filter 2: <b>887 – 2098 – 4234 Hz</b><br>Filter 3: 2098 – 4234 – 8000 Hz",
        "03_Speech_Recognition_Mel",
        ["exam2024:Q4"],
        "mel_exam2024_filters",
        ["priority:high"],
        batch="2",
    ),
    basic(
        "Prosody in speech — what does it include?",
        "Pitch (F0), duration, loudness, rhythm, intonation, prominence — NOT just spectral/formant features.",
        "03_Speech_Recognition_Mel",
        ["L04:prosody", "exam2025:Q1d"],
        batch="2",
    ),
    basic(
        "Whisper ASR architecture type?",
        "Encoder-decoder Transformer trained on large-scale weakly supervised speech data (multilingual, multitask).",
        "03_Speech_Recognition_Mel",
        ["L04:Whisper"],
        batch="2",
    ),
    basic(
        "What is core affect in dimensional emotion theory?",
        "Most elementary affective feelings (valence + arousal) — part of but not identical to a full emotional episode (which also includes cognitive appraisal, action tendencies).",
        "01_Affective_Computing",
        ["L02:dimensional"],
        batch="2",
    ),
    basic(
        "Exam 2025 Q3a: Why are RNNs suitable for sequential data?",
        "They maintain a <b>hidden state</b> across time steps that summarizes past inputs — natural fit for text, speech, and video sequences.",
        "02_Attention_Deep_Learning",
        ["exam2025:Q3a-i"],
        batch="2",
    ),
    basic(
        "RNN language modeling objective?",
        "J = −Σ_t log P(y_t | x₁…x_t) — maximize probability of next token given history. Training uses teacher forcing.",
        "02_Attention_Deep_Learning",
        ["L03:language_modeling"],
        batch="2",
    ),
    basic(
        "Biosensor pipeline for affect classification?",
        "Raw signal → artifact detection → feature extraction (HRV stats, SC phasic/tonic) → classifier (e.g. Random Forest) → valence/arousal prediction.",
        "01_Affective_Computing",
        ["L02:biosensor_pipeline"],
        batch="2",
    ),
    basic(
        "Fear Action Units (from lecture table)?",
        "AU1 + AU2 + AU4 + AU5 + AU7 + AU20 + AU26 (brow raisers, lid raiser, lip stretcher, jaw drop, etc.)",
        "01_Affective_Computing",
        ["L02:AU_table"],
        batch="2",
    ),
    basic(
        "Anger Action Units?",
        "AU4 + AU5 + AU7 + AU23 (Brow Lowerer, Upper Lid Raiser, Lid Tightener, Lip Tightener)",
        "01_Affective_Computing",
        ["L02:AU_table"],
        batch="2",
    ),
    basic(
        "Cross-entropy loss for classification?",
        "L = −Σ y_i · log(ŷ_i) — measures divergence between true distribution y and predicted ŷ. Used to train neural classifiers.",
        "02_Attention_Deep_Learning",
        ["L03:training"],
        batch="2",
    ),
]
